/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MailOutboxIndexRouteImport } from './routes/mail-outbox/index'
import { Route as FlowItemsIndexRouteImport } from './routes/flow-items/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as BrokersIndexRouteImport } from './routes/brokers/index'
import { Route as CustomersNewRouteImport } from './routes/customers/new'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'
import { Route as BrokersNewRouteImport } from './routes/brokers/new'
import { Route as BrokersBrokerIdRouteImport } from './routes/brokers/$brokerId'
import { Route as AuthSetupPasswordRouteImport } from './routes/auth/setup-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailOutboxIndexRoute = MailOutboxIndexRouteImport.update({
  id: '/mail-outbox/',
  path: '/mail-outbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowItemsIndexRoute = FlowItemsIndexRouteImport.update({
  id: '/flow-items/',
  path: '/flow-items/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersIndexRoute = BrokersIndexRouteImport.update({
  id: '/brokers/',
  path: '/brokers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersNewRoute = BrokersNewRouteImport.update({
  id: '/brokers/new',
  path: '/brokers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersBrokerIdRoute = BrokersBrokerIdRouteImport.update({
  id: '/brokers/$brokerId',
  path: '/brokers/$brokerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupPasswordRoute = AuthSetupPasswordRouteImport.update({
  id: '/auth/setup-password',
  path: '/auth/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/brokers/new': typeof BrokersNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/brokers/': typeof BrokersIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/flow-items/': typeof FlowItemsIndexRoute
  '/mail-outbox/': typeof MailOutboxIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/brokers/new': typeof BrokersNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/brokers': typeof BrokersIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/flow-items': typeof FlowItemsIndexRoute
  '/mail-outbox': typeof MailOutboxIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/brokers/new': typeof BrokersNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/brokers/': typeof BrokersIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/flow-items/': typeof FlowItemsIndexRoute
  '/mail-outbox/': typeof MailOutboxIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/brokers/$brokerId'
    | '/brokers/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/brokers/'
    | '/customers/'
    | '/flow-items/'
    | '/mail-outbox/'
    | '/settings/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/brokers/$brokerId'
    | '/brokers/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/brokers'
    | '/customers'
    | '/flow-items'
    | '/mail-outbox'
    | '/settings'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/brokers/$brokerId'
    | '/brokers/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/brokers/'
    | '/customers/'
    | '/flow-items/'
    | '/mail-outbox/'
    | '/settings/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupPasswordRoute: typeof AuthSetupPasswordRoute
  BrokersBrokerIdRoute: typeof BrokersBrokerIdRoute
  BrokersNewRoute: typeof BrokersNewRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
  BrokersIndexRoute: typeof BrokersIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  FlowItemsIndexRoute: typeof FlowItemsIndexRoute
  MailOutboxIndexRoute: typeof MailOutboxIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-outbox/': {
      id: '/mail-outbox/'
      path: '/mail-outbox'
      fullPath: '/mail-outbox/'
      preLoaderRoute: typeof MailOutboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-items/': {
      id: '/flow-items/'
      path: '/flow-items'
      fullPath: '/flow-items/'
      preLoaderRoute: typeof FlowItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/': {
      id: '/brokers/'
      path: '/brokers'
      fullPath: '/brokers/'
      preLoaderRoute: typeof BrokersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/new': {
      id: '/brokers/new'
      path: '/brokers/new'
      fullPath: '/brokers/new'
      preLoaderRoute: typeof BrokersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/$brokerId': {
      id: '/brokers/$brokerId'
      path: '/brokers/$brokerId'
      fullPath: '/brokers/$brokerId'
      preLoaderRoute: typeof BrokersBrokerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup-password': {
      id: '/auth/setup-password'
      path: '/auth/setup-password'
      fullPath: '/auth/setup-password'
      preLoaderRoute: typeof AuthSetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupPasswordRoute: AuthSetupPasswordRoute,
  BrokersBrokerIdRoute: BrokersBrokerIdRoute,
  BrokersNewRoute: BrokersNewRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  BrokersIndexRoute: BrokersIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  FlowItemsIndexRoute: FlowItemsIndexRoute,
  MailOutboxIndexRoute: MailOutboxIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
