/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as BrokersIndexRouteImport } from './routes/brokers/index'
import { Route as CustomersNewRouteImport } from './routes/customers/new'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'
import { Route as BrokersNewRouteImport } from './routes/brokers/new'
import { Route as BrokersBrokerIdRouteImport } from './routes/brokers/$brokerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersIndexRoute = BrokersIndexRouteImport.update({
  id: '/brokers/',
  path: '/brokers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersNewRoute = BrokersNewRouteImport.update({
  id: '/brokers/new',
  path: '/brokers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersBrokerIdRoute = BrokersBrokerIdRouteImport.update({
  id: '/brokers/$brokerId',
  path: '/brokers/$brokerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/brokers/new': typeof BrokersNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/brokers/': typeof BrokersIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/brokers/new': typeof BrokersNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/brokers': typeof BrokersIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/brokers/new': typeof BrokersNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/brokers/': typeof BrokersIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brokers/$brokerId'
    | '/brokers/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/brokers/'
    | '/customers/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brokers/$brokerId'
    | '/brokers/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/brokers'
    | '/customers'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/brokers/$brokerId'
    | '/brokers/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/brokers/'
    | '/customers/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrokersBrokerIdRoute: typeof BrokersBrokerIdRoute
  BrokersNewRoute: typeof BrokersNewRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
  BrokersIndexRoute: typeof BrokersIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/': {
      id: '/brokers/'
      path: '/brokers'
      fullPath: '/brokers/'
      preLoaderRoute: typeof BrokersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/new': {
      id: '/brokers/new'
      path: '/brokers/new'
      fullPath: '/brokers/new'
      preLoaderRoute: typeof BrokersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/$brokerId': {
      id: '/brokers/$brokerId'
      path: '/brokers/$brokerId'
      fullPath: '/brokers/$brokerId'
      preLoaderRoute: typeof BrokersBrokerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrokersBrokerIdRoute: BrokersBrokerIdRoute,
  BrokersNewRoute: BrokersNewRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  BrokersIndexRoute: BrokersIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
